### ISSUE TITLE
Error due to ambiguous ostrstream while running bfc.C in ROOT6

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#126]
When I try to run one of our tests in ROOT6 environment I get the following error:

```
Processing bfc.C(10, "pp2017,StiCA,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")...
In file included from input_line_37:1:
In file included from /star-sw/StRoot/macros/bfc.C:19:
In file included from /star-sw/.sl88_gcc789/include/StBFChain.h:22:
In file included from /star-sw/.sl88_gcc789/include/StChain.h:22:
In file included from /star-sw/.sl88_gcc789/include/StMaker.h:26:
/star-sw/.sl88_gcc789/include/StMessMgr.h:108:26: error: reference to 'ostrstream' is ambiguous
class StMessMgr : public ostrstream {
                         ^
/star-sw/.sl88_gcc789/include/Stsstream.h:15:7: note: candidate found by name lookup is 'ostrstream'
class ostrstream : public std::ostringstream {
      ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward/strstream:143:9: note: candidate found by name lookup is 'std::ostrstream'
  class ostrstream : public basic_ostream<char>
```

Any suggestions how to fix this? @perevbnlgov @klendathu2k

**Comment by klendathu2k** [comment]
Hi Dmitri,

This is exactly the problem I mentioned on Wednesday (and just getting 
back to now).

The problem is that we have a duplicate ostrstream class defined here--
StRoot/St_base/Stsstream.h

I guess in ROOT6, an #include has been exposed somewhere that leads to a 
conflict
with the above code.  So...

A possible solution would be to delete everything in Stsstream.h and 
replace with
#include <strstream>

Testing in my geant4star area... I can at least load StMessMgr (which is 
usually where
things fail for me).

Warnings about deprecated code are being issued during compilation, 
though... code has been
deprecated since 1998.  So we should be careful using this because it 
could disappear at any moment...

Victor-- could you remind us of the history behind Stssream.h, and 
whether we still
need it or not?  Or what a better solution would be?

Cheers,
Jason

**Comment by plexoos** [comment]
> A possible solution would be to delete everything in Stsstream.h and replace with `#include <strstream>`

So, basically you are proposing to drop our local implementation of `ostrstream` https://github.com/star-bnl/star-sw/blob/main/StRoot/St_base/Stsstream.h#L15-L27 and rely on the deprecated one in `<strstream>`
Hm... I believe the local `ostrstream` **was** introduced **because** it has been deprecated relatively long time ago and probably already missing in some releases.

Anyway, for now I just renamed our 'ostrstream' to something different so it does not collide with the std:: one from wherever it is coming from. Enclosing it in a star:: namespace would probably be a better solution... Fortunately, we don't have many instances where `ostrstream` is used in the code.

**Comment by perevbnlgov** [comment]
> Victor-- could you remind us of the history behind Stssream.h, and
Yes I could. At the very beginning it was used very old and very ugly 
version of stream.
When more new version came, it became completely incompatible with the 
existing code.
Especially with Jeff Porter DB and Gene StMessage. This Stiustream was 
used to keep
compatibility with old version of iostream and new one. When Root6 + new 
C++ compiler
arised, it became not compatible again. I completely rewrote this 
iostream and change
a lot of old code to be compatible with the latest iostrea version.
Unfortunately, as I have already told, O did not save it in CVS and 
deleted by mistake.
When I was trying to recover, I used less strict version of C++ (from 
Yuri)
and much less changes were needed to comply with this iostream problem.
Standard compilation was OK. But probably my easy way of fixing it, is 
too easy.
So I need to come back and fix it using the latest version of iostream.
Victor

**Comment by klendathu2k** [comment]
Thanks.  If I read correctly, coming up with a solution is a non-trivial 
task.
First must re-implment your *stream, then modify many STAR codes.

So... just thinking out loud.  Rather than reinventing the deprecated 
wheel...

Why not move to something that replaced ostrstream?
https://stackoverflow.com/questions/10849656/what-should-i-use-instead-of-stdostrstream

Specifically...
std::stringstream

**Comment by perevbnlgov** [comment]
> Why not move to something that replaced ostrstream?
> https://stackoverflow.com/questions/10849656/what-should-i-use-instead-of-stdostrstream
> Specifically...
It was exactly what i did and lost
   <sstream>, basic_stringstream
Victor

**Comment by plexoos** [comment]
> > Why not move to something that replaced ostrstream? https://stackoverflow.com/questions/10849656/what-should-i-use-instead-of-stdostrstream Specifically...
>
> It was exactly what i did and lost <sstream>, basic_stringstream

Is there anything wrong with renaming the redefined `ostrstream` to something else in order to avoid collision with `std::ostrstream`?

**Comment by klendathu2k** [comment]
Nothing wrong, per se.  But we're maintaining a piece of code that can 
be replaced by something
in the STL.  I think it's worth a little effort here.  I have started to 
refactor codes to make this
replacement.  If I can't finish (leaving for vacation days early 
tomorrow), I'll push the branch in
whatever state it is and point you + Victor to it.

**Comment by klendathu2k** [comment]
FYI--

On my repo I have a possible solution, replacing ostrstream w/ 
ostringstream.
https://github.com/klendathu2k/star-sw-1/tree/star-root6-stringstream

Code compiles.  Have made no other tests than that.
